
export const KICK_STREAMERS: { username: string; tags: string[]; character: string }[] = [
  { username: 'SXB', tags: ['CIA', 'CIA Leaders', 'DO Commander', 'DO'], character: 'Abdulsamad Alqurashi' },
  { username: 'https://kick.com/ysmo', tags: ['CIA', 'CIA Deputy'], character: 'Agent X' },
  { username: 'Osamah', tags: ['CIA', 'CIA Leader'], character: 'Alexander Mahon' },
  { username: 'MOLO101', tags: ['CIA', 'DS Commander', 'DS'], character: 'Dr.Anderw' },
  { username: 'lMeshari4', tags: ['CIA', 'CIA Leaders', 'DA Commander'], character: 'Michael Conner' },
  { username: 'tmnaa', tags: ['CIA', 'DO Deputy'], character: 'Abdullah Alshmmari' },
  { username: 'RpWy', tags: ['CIA', 'DO'], character: 'Abdullah Khalid' },
  { username: 'AbuSwe7l', tags: ['CIA', 'ALPHA Son'], character: 'Rick Mahon' },
  { username: 'IC4C', tags: ['CIA', 'CIA Leaders'], character: 'Saif Alansary' },
  { username: 'Ab2dy', tags: ['CIA', 'DO'], character: 'Abdullah Abd Al-Aziz' },
  { username: 'brof2', tags: ['CIA', 'DO'], character: 'Brof' },
  { username: 'IB6h', tags: ['CIA', 'Executive Director'], character: 'Damien Silver Beta' },
  { username: 'PROMT3B', tags: ['CIA', 'Death Battelion Deputy'], character: 'DON' },
  { username: 'Fahad', tags: ['CIA', 'DO'], character: 'Fahad Saad' },
  { username: 'Muvxn', tags: ['CIA', 'DO'], character: 'Musab Al Sultan' },
  { username: 'CKIV', tags: ['CIA', 'Border Breaking Battalion', 'DO'], character: 'Frank Peter | Agro' },
  { username: 'Azeez', tags: ['CIA', 'Flight Field Commander'], character: 'Eziar Qab' },
  { username: 'xEid', tags: ['CIA', 'CIA Leaders','Death Battelion Commanders', 'DO'], character: 'Bob Marley | Rambo' },
  { username: 'Firas', tags: ['CIA', 'DO'], character: 'Snop Marley' },
  { username: '7omah', tags: ['CIA', 'CIA Pilot', 'DI Deputy'], character: 'Merf' },
  { username: 'Zeeyadx', tags: ['CIA', 'DO'], character: 'Agent Hunter' },
  { username: 'xlxwi', tags: ['CIA', 'DO'], character: 'Ali Abdullah' },
  { username: 'Dark12', tags: ['CIA', 'DA'], character: 'Alex Michael' },
  { username: 'kawd10', tags: ['CIA', 'DA Deputy'], character: 'Martin Peterson' },
  { username: 'Vilon', tags: ['CIA', 'DO'], character: 'Agent Silver Bullet' },
  { username: '7soo', tags: ['CIA', 'Border Breaking Battalion Leader'], character: 'Paul' },
  { username: 'LiRx', tags: ['CIA', 'Border Breaking Battalion Deputy'], character: 'Marcus' },
  { username: 'iikhd7', tags: ['CIA', 'Border Breaking Battalion'], character: 'Billy' },
  { username: 'Jntel', tags: ['CIA', 'Border Breaking Battalion'], character: 'Tango' },
  { username: 's6mito', tags: ['CIA', 'DO'], character: 'Satam Al Otaibi' },
  { username: 'vSaleh', tags: ['CIA', 'DO'], character: 'Saleh Alenzi "Agent-Ninja"' },
  { username: 'INQ', tags: ['CIA', 'CIA Leaders'], character: 'James Arthur' },
  { username: 'mesh7', tags: ['CIA', 'DO'], character: 'Meshal Salman' },
  { username: 'Sult', tags: ['CIA', 'DO'], character: 'Sulatn Alotaibi | Zolo' },
  { username: 'itsOG', tags: ['Agent'], character: 'Talq AlSbi3i' },
  { username: 'MTNEWS', tags: ['Agent'], character: '3amar Bin Abdulhamid' },
  { username: 'xMusaad', tags: ['Agent'], character: 'Musa3d' },
  { username: '1RWi', tags: ['CIA', 'Death Battelion Deputy Commanders'], character: 'Ms.Caplin' },
  { username: 'odn35', tags: ['CIA', 'DS Deputy', 'DS'], character: 'Benny Surge "Agent-Gaster"' },
  { username: 'VMalik', tags: ['CIA', 'DS Deputy', 'DS'], character: 'Munir Almalky' },
  { username: 'iABS', tags: ['CIA'], character: 'Aba Alhreth' },
  { username: 'abu_saad3', tags: ['CIA', 'DS'], character: 'Ali Bin Saad' },
  { username: 'cRaed', tags: ['CIA', 'DS'], character: 'Wiliam Coby' },
  { username: '71sky', tags: ['CIA', 'DS'], character: 'Skylar Scott' },
  { username: 'sniperxzaid', tags: ['CIA', 'DS'], character: 'Zaid Muhammad' },
  { username: '0xsultan', tags: ['CIA', 'DS'], character: 'Lysander Restova' },
  { username: 'tqrolld', tags: ['CIA', 'DS'], character: 'Victor Rundn' },
  { username: 'Fwaz', tags: ['CIA', 'CIA Leaders', 'DOU Commander'], character: 'Fwaz Jnaza' },
  { username: 'D7MX', tags: ['CIA', 'CIA Leaders', 'Executive Director'], character: 'Echo' },
  { username: 'Abdullahx', tags: ['CIA', 'CIA Deputy'], character: 'Bravo' },
];

export const POLLING_INTERVAL_SECONDS: number = 90;
