
export const KICK_STREAMERS: { username: string; tags: string[]; character: string }[] = [
  { username: 'SXB', tags: ['CIA', 'CIA Leaders', 'DO Director', 'DO'], character: 'Abdulsamad Alqurashi' },
  { username: 'ysmo', tags: ['CIA', 'CIA Deputy Director'], character: 'Agent X' },
  { username: 'Osamah', tags: ['CIA', 'CIA Director'], character: 'Alexander Mahon' },
  { username: 'MOLO101', tags: ['CIA', 'DS Director', 'DS'], character: 'Dr.Anderw' },
  { username: 'lMeshari4', tags: ['CIA', 'CIA Leaders', 'DA Director'], character: 'Michael Conner' },
  { username: 'tmnaa', tags: ['CIA', 'DO Deputy Director'], character: 'Abdullah Alshmmari' },
  { username: 'RpWy', tags: ['CIA', 'DO'], character: 'Abdullah Khalid' },
  { username: 'Ab2dy', tags: ['CIA', 'DO'], character: 'Abdullah Abd Al-Aziz' },
  { username: 'brof2', tags: ['CIA', 'DO'], character: 'Brof' },
  { username: 'PROMT3B', tags: ['CIA', 'Death Battelion Deputy'], character: 'DON' },
  { username: 'Fahad', tags: ['CIA', 'DO'], character: 'Fahad Saad' },
  { username: 'Muvxn', tags: ['CIA', 'DO'], character: 'Musab Al Sultan' },
  { username: 'CKIV', tags: ['CIA', 'DO'], character: 'Frank Peter' },
  { username: 'Azeez', tags: ['CIA', 'Flight Field Director'], character: 'Eziar Qab' },
  { username: 'xEid', tags: ['CIA', 'CIA Leaders','Death Battelion Commander', 'DO'], character: 'Bob Marley | Rambo' },
  { username: 'Firas', tags: ['CIA', 'DO'], character: 'Snop Marley' },
  { username: '7omah', tags: ['CIA', 'CIA Pilot', 'DI Deputy'], character: 'Merf' },
  { username: 'Zeeyadx', tags: ['CIA', 'DO'], character: 'Zeeyad Alshmmari' },
  { username: 'Vilon', tags: ['CIA', 'DO'], character: 'Akai' },
  { username: 's6mito', tags: ['CIA', 'DO'], character: 'Satam Al Otaibi' },
  { username: 'INQ', tags: ['CIA', 'CIA Leaders'], character: 'James Arthur' },
  { username: 'mesh7', tags: ['CIA', 'DO'], character: 'Meshal Salman' },
  { username: 'Sult', tags: ['CIA', 'DO'], character: 'Sulatn Alotaibi | Zolo' },
  { username: 'itsOG', tags: ['Agent'], character: 'Talq AlSbi3i' },
  { username: 'MTNEWS', tags: ['Agent'], character: '3amar Bin Abdulhamid' },
  { username: 'xMusaad', tags: ['Agent'], character: 'Musa3d' },
  { username: 'odn35', tags: ['CIA', 'DS Deputy', 'DS'], character: 'Jaster' },
  { username: 'VMalik', tags: ['CIA', 'DS Deputy', 'DS'], character: 'Munir Almalky' },
  { username: 'iABS', tags: ['CIA'], character: 'Aba Alhreth' },
  { username: 'abu_saad3', tags: ['CIA', 'DS'], character: 'Anonymous' },
  { username: 'craed', tags: ['CIA', 'DS'], character: 'Wiliam Coby' },
  { username: 'sniperxzaid', tags: ['CIA', 'DS'], character: 'Zaid Muhammad' },
  { username: '0xsultan', tags: ['CIA', 'DS'], character: 'Anonymous' },
  { username: 'tqrolld', tags: ['CIA', 'DS'], character: 'None' },
];

export const POLLING_INTERVAL_SECONDS: number = 90;
